version: '3'

services:
  
  app:
    image: node:14 
    container_name: credit-approval-app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000" 
    environment:
      - DATABASE_HOST=127.0.0.1
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=creditsystem
    depends_on:
      - db
    command: npm start

 
  db:
    image: mysql:8 
    container_name: credit-approval-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: creditsystem
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306" 
    volumes:
      - ./db_data:/var/lib/mysql

 

networks:
  default:
    external:
      name: your_custom_network 